### ISSUE TITLE
Ограничить редактирование подтвержденных направлений

### ISSUE THREAD

**Issue by telminov** [Egorka96/med-org-portal#35]
Редактирование и удаление. Возможно с какими-то ограничениями. Например, пока нет заявки в МИС

**Comment by Egorka96** [comment]
Редактирование и удаление уже есть. 
Единственный момент, что редактировать и удалять можно даже после создания заявки, этот момент я не продумал. Тут думаю нужно ограничение добавить

**Comment by Egorka96** [comment]
Если по направлению уже есть заявка, то редактировать направление нельзя
